@FilesStorage_HostAddress = http://localhost:8088

POST {{FilesStorage_HostAddress}}/api/File 
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="text.txt"

< ./text.txt
--WebAppBoundary--

### 
GET {{FilesStorage_HostAddress}}/api/File/f2f84008-f764-48d7-8dc9-4fe115701e5a
Accept: application/json

###


