@FilesStorage_HostAddress = https://sfs.wardensquad.fr

POST {{FilesStorage_HostAddress}}/api/File 
Content-Type: multipart/form-data; boundary=WebAppBoundary
Token: tFsxxz+2B7dOEEHwxiyDJCuIJZQHg7cFN376mw+C31Y=

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="img.png"

< ./img.png
--WebAppBoundary--

### 
GET {{FilesStorage_HostAddress}}/api/File/9189530f-f5e4-419c-9bb2-3ea3807f7f8


###


